# Generated by Django 4.1.5 on 2023-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_razorpay', '0002_remove_transaction_name_transaction_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='balance',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing')], default='INCOMING', max_length=15),
        ),
    ]
