# Generated by Django 4.1.5 on 2023-01-31 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_razorpay', '0004_alter_transaction_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_fee', models.DecimalField(decimal_places=2, default=200, max_digits=12, verbose_name='membership_fee')),
                ('gateway_charges', models.DecimalField(decimal_places=2, default=2, max_digits=12, verbose_name='gateway_charges')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at')),
            ],
        ),
    ]
